version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: patient-service-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    build:
      context: .
      dockerfile: ./patient-service/Dockerfile
    container_name: patient-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    ports:
      - "4000:4000"
    networks:
      - internal

  billing-service:
    build:
      context: .
      dockerfile: ./billing-service/Dockerfile
    container_name: billing-service
    volumes:
      - ./billing-service/target:/app/billing-service/target:rw
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal


volumes:
  postgres_data:

networks:
  internal:
